// Literal vectors transcribed from the pinned Rust tests, never generated by this port.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { truncateTokens, truncateBytes } from '../src/codex-truncate.ts';
import { isInjectedUserText, renderSession } from '../src/rollout.ts';
import { evidenceMessages } from '../src/v2.ts';
import { parseMemoryCitation, threadIdsFromCitation } from '../src/read-path.ts';
import { MemoryStore } from '../src/store.ts';
import { readMemory, searchMemories } from '../src/memory-backend.ts';

test('upstream string truncate tests: zero, under budget and UTF-8 byte/token markers',()=>{
  // vendor/codex/src/string_truncate_tests.rs: truncate_with_token_budget_* and truncate_middle_*.
  assert.equal(truncateTokens('short output',100),'short output');
  assert.equal(truncateTokens('abcdef',0),'…2 tokens truncated…');
  const input='😀😀😀😀😀😀😀😀😀😀\nsecond line with text\n';
  assert.equal(truncateTokens(input,8),'😀😀😀😀…8 tokens truncated… line with text\n');
  assert.equal(truncateBytes(input,20),'😀😀…21 chars truncated…with text\n');
});

test('upstream citations_tests.rs: legacy IDs, rollout IDs and deduplicated entries',()=>{
  const first='00000000-0000-0000-0000-000000000001',second='00000000-0000-0000-0000-000000000002';
  const legacy=parseMemoryCitation([`<memory_citation>\n<citation_entries>\nMEMORY.md:1-2|note=[x]\n</citation_entries>\n<thread_ids>\n${first}\nnot-a-uuid\n${second}\n</thread_ids>\n</memory_citation>`]);
  assert.deepEqual(threadIdsFromCitation(legacy),[first,second]);
  assert.deepEqual(threadIdsFromCitation(parseMemoryCitation([`<memory_citation>\n<rollout_ids>\n${first}\n</rollout_ids>\n</memory_citation>`])),[first]);
  const parsed=parseMemoryCitation([`<citation_entries>\nMEMORY.md:1-2|note=[summary]\nrollout_summaries/foo.md:10-12|note=[details]\n</citation_entries>\n<rollout_ids>\n${first}\n${second}\n${first}\n</rollout_ids>`]);
  assert.deepEqual(parsed.entries,[{path:'MEMORY.md',lineStart:1,lineEnd:2,note:'summary'},{path:'rollout_summaries/foo.md',lineStart:10,lineEnd:12,note:'details'}]);
  assert.deepEqual(parsed.rolloutIds,[first,second]);
});
test('upstream state_memories.rs: claim_stage1_jobs_filters_by_age_idle_and_current_thread',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'pcm-state-vector-'));const store=new MemoryStore(path.join(root,'state.sqlite'));
  t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true});});
  const now=Date.now();
  // Upstream CLI source maps to pi's interactive source; timestamps/order/expected ID are unchanged.
  for(const [id,age] of [['current',0],['fresh',3600000],['just-under-idle',12*3600000-60000],['eligible-idle',12*3600000+60000],['old',31*86400000]])store.upsertThread({id,rolloutPath:path.join(root,id),cwd:root,updatedAtMs:now-age,memoryMode:'enabled',gitBranch:null,source:'interactive'});
  const claims=store.claimStage1JobsForStartup({currentThreadId:'current',scanLimit:1,maxClaimed:5,maxAgeDays:30,minIdleHours:12,leaseSeconds:3600});
  assert.equal(claims.length,1);assert.equal(claims[0].thread.id,'eligible-idle');
});
test('upstream ext_tests.rs: read_tool_reads_memory_file and multiple/windowed query responses',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'pcm-read-vector-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  const file=path.join(root,'MEMORY.md');
  fs.writeFileSync(file,'first line\nsecond needle line\nthird line\n');
  assert.deepEqual(readMemory(root,{path:'MEMORY.md',line_offset:2,max_lines:1}),{path:'MEMORY.md',content:'second needle line\n',start_line_number:2,truncated:true});
  fs.writeFileSync(file,'alpha only\nneedle only\nalpha needle\n');
  assert.deepEqual(searchMemories(root,{queries:['alpha','needle'],case_sensitive:false}),{
    queries:['alpha','needle'],match_mode:{type:'any'},path:null,matches:[
      {path:'MEMORY.md',match_line_number:1,content_start_line_number:1,content:'alpha only',matched_queries:['alpha']},
      {path:'MEMORY.md',match_line_number:2,content_start_line_number:2,content:'needle only',matched_queries:['needle']},
      {path:'MEMORY.md',match_line_number:3,content_start_line_number:3,content:'alpha needle',matched_queries:['alpha','needle']},
    ],next_cursor:null,truncated:false,
  });
  fs.writeFileSync(file,'alpha\nmiddle\nneedle\n');
  assert.deepEqual(searchMemories(root,{queries:['alpha','needle'],match_mode:{type:'all_within_lines',line_count:3}}),{
    queries:['alpha','needle'],match_mode:{type:'all_within_lines',line_count:3},path:null,matches:[{path:'MEMORY.md',match_line_number:1,content_start_line_number:1,content:'alpha\nmiddle\nneedle',matched_queries:['alpha','needle']}],next_cursor:null,truncated:false,
  });
});
test('upstream rollout_input_tests.rs: classifies_memory_excluded_fragments',()=>{
  for(const [text,expected] of [
    ['# AGENTS.md instructions for /tmp\n\n<INSTRUCTIONS>\nbody\n</INSTRUCTIONS>',true],
    ['# AGENTS.md instructions\n\n<INSTRUCTIONS>\nbody\n</INSTRUCTIONS>',true],
    ['<skill>\n<name>demo</name>\n<path>skills/demo/SKILL.md</path>\nbody\n</skill>',true],
    ['<environment_context>\n<cwd>/tmp</cwd>\n</environment_context>',false],
    ['<subagent_notification>{"agent_id":"a","status":"completed"}</subagent_notification>',false],
  ])assert.equal(isInjectedUserText(text),expected);
});
test('upstream rollout_input_tests.rs: extraction_chunks_preserve_unicode_evidence_with_bounded_messages',()=>{
  const evidence='User correction: 🐈\n'.repeat(2000),messages=evidenceMessages(evidence);
  for(const m of messages){assert.equal(m.role,'user');assert.ok(Buffer.byteLength(m.content[0].text)<9000);}
  assert.equal(messages.map(m=>m.content[0].text).join(''),evidence);
});
test('normalized pi evidence preserves branch IDs, explicit phase and question-answer provenance',t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'pcm-evidence-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  const messages=[
    {role:'assistant',phase:'commentary',source:'interactive',content:[{type:'text',text:'Checking.'}]},
    {role:'assistant',stopReason:'toolUse',content:[{type:'text',text:'No explicit phase.'},{type:'toolCall',id:'q',name:'request_user_input',arguments:{questions:[{id:'choice',question:'Pick?'}]}}]},
    {role:'toolResult',toolCallId:'q',toolName:'request_user_input',content:[{type:'text',text:'{"answers":{"choice":{"answers":["A"]}}}'}]},
    {role:'user',internal_chat_message_metadata_passthrough:{content_item_kinds:['multi_agent.report']},content:'Agent findings'},
  ];
  const file=path.join(root,'s.jsonl');fs.writeFileSync(file,[{type:'session',id:'s',cwd:root},...messages.map((message,i)=>({type:'message',id:String(i),parentId:i?String(i-1):null,message}))].map(JSON.stringify).join('\n'));
  const {rows,evidence}=renderSession(file);
  assert.deepEqual(rows.map(row=>row.split('\n')[0]),['[assistant commentary]','[assistant final]','[tool call]','[human user]','[other agent]']);
  assert.match(rows[3],/Assistant question:.*Pick\?/);assert.match(rows[3],/Human reply:/);
  assert.equal(evidence[0].source,'interactive');assert.equal(evidence[1].source,'unknown');assert.equal(evidence[1].phase,null);
  assert.equal(evidence[3].parentId,'2');assert.equal(evidence[0].branchHead,'3');
});
