// Git-baseline workspace diff. Mirrors codex-git-utils baseline.rs + memories/write/src/workspace.rs:
// the memory root is its own throwaway git repo; after each successful consolidation the repo is
// re-created with a single commit so history is never retained (deleted memories don't linger in objects).
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { WORKSPACE_DIFF } from "./config.ts";
import { ensureLayout } from "./storage.ts";

export type Change = { status: "added" | "modified" | "deleted" | "renamed" | "typechange" | "unknown"; path: string };
export type BaselineDiff = { changes: Change[]; unifiedDiff: string };

const GIT_ENV = { ...process.env, GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_GLOBAL: process.platform === "win32" ? "NUL" : "/dev/null", HOME: process.env.HOME ?? process.env.USERPROFILE ?? "" };
const IDENT = ["-c", "user.name=pi-codex-memory", "-c", "user.email=memory@localhost", "-c", "core.autocrlf=false", "-c", "core.safecrlf=false", "-c", "commit.gpgsign=false", "-c", "core.hooksPath=/dev/null"];

function git(root: string, args: string[], opts: { allowFail?: boolean } = {}) {
  const r = spawnSync("git", [...IDENT, ...args], { cwd: root, encoding: "utf8", env: GIT_ENV, maxBuffer: 64 * 1024 * 1024 });
  if (r.error) throw r.error;
  if (r.status !== 0 && !opts.allowFail) throw new Error(`git ${args[0]} failed: ${(r.stderr || r.stdout).trim()}`);
  return r;
}

export function gitAvailable(): boolean {
  const r = spawnSync("git", ["--version"], { encoding: "utf8" });
  return !r.error && r.status === 0;
}

function baselineUsable(root: string): boolean {
  if (!fs.existsSync(path.join(root, ".git"))) return false;
  return git(root, ["rev-parse", "--verify", "HEAD"], { allowFail: true }).status === 0;
}

function initBaseline(root: string) {
  fs.rmSync(path.join(root, ".git"), { recursive: true, force: true });
  git(root, ["init", "-q"]);
  fs.writeFileSync(path.join(root, ".git", "info", "exclude"), `${WORKSPACE_DIFF.FILENAME}\n`);
  git(root, ["add", "-A", "--", "."]);
  git(root, ["commit", "-q", "--allow-empty", "-m", "memory baseline"]);
}

/** prepare_memory_workspace: ensure layout, drop stale diff artifact, ensure usable baseline. */
export function prepareMemoryWorkspace(root: string) {
  ensureLayout(root);
  removeWorkspaceDiff(root);
  if (!baselineUsable(root)) initBaseline(root);
}

export function removeWorkspaceDiff(root: string) {
  fs.rmSync(path.join(root, WORKSPACE_DIFF.FILENAME), { force: true });
}

/** diff_since_latest_init: status + unified diff of worktree vs. the single baseline commit. */
export function memoryWorkspaceDiff(root: string): BaselineDiff {
  removeWorkspaceDiff(root);
  git(root, ["add", "-A", "-N", "--", "."]); // intent-to-add so untracked files show in diff
  const status = git(root, ["status", "--porcelain=v1", "--untracked-files=all", "--", "."]).stdout;
  const changes: Change[] = [];
  for (const line of status.split("\n")) {
    if (!line.trim()) continue;
    const code = line.slice(0, 2), file = line.slice(3).replace(/^"|"$/g, "");
    const s: Change["status"] = /A|\?/.test(code) ? "added" : /D/.test(code) ? "deleted" : /R/.test(code) ? "renamed" : /T/.test(code) ? "typechange" : /M/.test(code) ? "modified" : "unknown";
    changes.push({ status: s, path: file.includes(" -> ") ? file.split(" -> ")[1] : file });
  }
  const unifiedDiff = changes.length ? git(root, ["diff", "--no-color", "--no-ext-diff", "HEAD", "--", "."]).stdout : "";
  return { changes, unifiedDiff };
}

export function renderWorkspaceDiffFile(diff: BaselineDiff): string {
  let out = "# Memory Workspace Diff\n\nGenerated by pi-codex-memory before Phase 2 memory consolidation. Read this file first and do not edit it.\n\n## Status\n";
  if (!diff.changes.length) return out + "- none\n";
  for (const c of diff.changes) out += `- ${c.status} ${c.path}\n`;
  out += "\n## Diff\n\n```diff\n";
  if (Buffer.byteLength(diff.unifiedDiff) <= WORKSPACE_DIFF.MAX_BYTES) {
    out += diff.unifiedDiff.endsWith("\n") || !diff.unifiedDiff ? diff.unifiedDiff : diff.unifiedDiff + "\n";
  } else {
    out += Buffer.from(diff.unifiedDiff).subarray(0, WORKSPACE_DIFF.MAX_BYTES).toString("utf8").replace(/\uFFFD+$/, "") + `\n\n[workspace diff truncated at ${WORKSPACE_DIFF.MAX_BYTES} bytes]\n`;
  }
  return out + "```\n";
}

export function writeWorkspaceDiff(root: string, diff: BaselineDiff) {
  fs.writeFileSync(path.join(root, WORKSPACE_DIFF.FILENAME), renderWorkspaceDiffFile(diff));
}

/** reset_git_repository: remove the diff artifact, then re-create the repo with one commit. */
export function resetMemoryWorkspaceBaseline(root: string) {
  removeWorkspaceDiff(root);
  initBaseline(root);
}
